version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "HelloWorldPythonLambdaApp"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-m7fzw5ja7vdu"
s3_prefix = "HelloWorldPythonLambdaApp"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
